### ISSUE TITLE
Issues when compiling ELPA in LUMI with CRAY compilers.

### ISSUE THREAD

**Issue by fedepedron** [marekandreas/elpa#32] opened 2023-02-16 13:45 UTC
Hello, I would like to report three different issues found when compiling ELPA ( 2022.11.001 )  in the LUMI supercomputer.
I have successfully managed to compile and run with the libraries (both with and without AMD gpu support) after addressing those appropriately.

---

1) `elpa_impl_math_template.F90 does not conform to FORTRAN standards and thus cray compilers fail. The issue lies in the following lines: 

https://github.com/marekandreas/elpa/blob/bea1f0ff8a5c7defdb1a7fc595b286cd55d326c9/src/elpa_impl_math_template.F90#L889-L896

According to [GNU standards](https://gcc.gnu.org/wiki/GFortranStandards), there cannot be a comment-only line within a line continuation. While I think that Cray is being very pedantic about it, changing those lines to something like the following fixes the issue:

```fortran
    subroutine elpa_solve_tridiagonal_&
                    &ELPA_IMPL_SUFFIX&
#ifdef REALCASE
#ifdef DOUBLE_PRECISION_REAL
                    &_c(handle, d_p, e_p, q_p, error) bind(C, name="elpa_solve_tridiagonal_d")
#endif
#ifdef SINGLE_PRECISION_REAL
                    &_c(handle, d_p, e_p, q_p, error) bind(C, name="elpa_solve_tridiagonal_f")
#endif
#endif
#ifdef COMPLEXCASE
#ifdef DOUBLE_PRECISION_COMPLEX
                    &_c(handle, d_p, e_p, q_p, error) !bind(C, name="elpa_solve_tridiagonal_dc")
#endif
#ifdef SINGLE_PRECISION_COMPLEX
                    &_c(handle, d_p, e_p, q_p, error) !bind(C, name="elpa_solve_tridiagonal_fc")
#endif
#endif
```
---

2) C and C++ tests should be disabled. I was not able to gather more information on these, but in case you need it, the errors I found are as follows:

* CPP tests fail to compile with a `“source file is not valid UTF-8 fatal error”` It seems as if the compiler was trying to re-compile from the object files instead of the source *.cpp files.

* C tests fail with this same error in all of the validate_* files, probably due to a linking issue.  :
```
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_size.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_cache.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_start.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_size.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_cache.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
ld.lld: error: ./.libs/libelpa.so: undefined reference to .omp_offloading.img_start.cray_amdgcn-amd-amdhsa [--no-allow-shlib-undefined]
```

---
3) Last but not least, when loading certain combinations of modules, libtool adds two dangling "-L" at the end of the postdeps variable. For example:

`postdeps="-lc -lcsup -lgcc_eh -lm -lclang_rt.craypgo-x86_64 -lgcc -lclang_rt.builtins-x86_64 `**`-L -L`**`"`

This results in a compiler crash saying that "-L" cannot be empty. I could not backtrace the whole thing, but apparently something happens when configure is parsing the environment.

My solution for now is to remove those extra "-L" from libtool after the configure step is done.

---

If I can provide any additional information on this, please do let me know!

**Comment by marekandreas** [comment] 2023-02-16 16:00
Hi @fedepedron ,

thank you for testing ELPA on LUMI with the CRAY compilers. We have used on LUMI the gnu programming environment.
Concerning your issues.

1. You are right! Will be fixed, asap.
2. Ok, this is strange and needs more debugging. But as you pointed out, one can circumvent these problems, by not building the C and C++ test binaries (which of course, will still keep ELPA functional, and still provide the C and C++ interfaces)
3. This is the most ugly problem, since it requires looking into the internals of autoconf. We will have a look where the double "-L" is introduced, but this might take some time

**Comment by fedepedron** [comment] 2023-02-17 08:59
Thanks for the quick reply :)

n°2 is not clear to me whether the build system or cray is doing anything weird, but definitely n°3 is ugly. I did have a look at the environment variables via printenv to see if there was anything clear, but nothing seemed suspicious. 

If you still have access to LUMI, you can reproduce this as follows:

default modules -> no "-L -L" in libtool after configure
module load rocm -> no "-L -L" in libtool after configure
module load craype-accel-amd-gfx90a → “-L -L ” appears in libtool after configure

I hope this helps!

**Comment by yizeyi18** [comment] 2023-10-23 08:39
About the second issue, maybe it is because the compiler recognizes the binary file as some source code according to some certain flags.

Issue [https://github.com/ROCm-Developer-Tools/HIP/issues/2167](url) from hip mentioned the case, and I reproduced that by "amdclang +x hip xxx.o ...". The issue may got fixed by modify flags in configure/Makefile. By the way, the C/CXX tests contains only code on CPU(and link to compiled lib/binary), and therefore there is no need to compile them with special flags/compiler frontend.

**Closed** 2024-02-28 09:56 UTC
